# Prototype clean copernicus

In [1]:
import pandas as pd
import os

# Set

In [ ]:
year = 2024

    # cmems_mod_med_phy-tem_anfc_4.2km_P1D-m
    # cmems_mod_med_bgc-pft_anfc_4.2km_P1D-m
product_name = 'cmems_mod_med_bgc-pft_anfc_4.2km_P1D-m'
input_path = "../data/raw"
df_name = f"{product_name}_{year}.parquet"

export_path = '../data/interim'
export_name = f"cleaned_{df_name}"
out = os.path.join(export_path, export_name)

# Import

In [ ]:
input = os.path.join(input_path, df_name)
df = pd.read_parquet(input)

# Check unique depth

In [4]:
df.head()

,depth,latitude,longitude,time,chl,diatoC,diatoChla,dinoC,dinoChla,nanoC,nanoChla,phyc,picoC,picoChla,zooc
0,1.018237,45.479168,13.166667,2024-01-01,0.432612,1.021826,0.045620,0.072453,0.003021,1.577424,0.132453,1.020759,9.577404,0.251518,1.292462
1,1.018237,45.479168,13.166667,2024-01-02,0.409951,0.959496,0.042592,0.065867,0.002696,1.508388,0.125726,0.969965,9.105830,0.238936,1.269215
2,1.018237,45.479168,13.166667,2024-01-03,0.387921,0.918257,0.040214,0.065525,0.002599,1.446924,0.118920,0.926805,8.690953,0.226188,1.249478
3,1.018237,45.479168,13.166667,2024-01-04,0.367288,0.876112,0.037932,0.063349,0.002475,1.385913,0.112419,0.885613,8.301986,0.214462,1.226269
4,1.018237,45.479168,13.166667,2024-01-05,0.347252,0.804106,0.034945,0.050663,0.002009,1.309341,0.106248,0.834719,7.852520,0.204050,1.191745

In [5]:
if len(df['depth'].unique()) != 1:
    raise ValueError("DataFrame contains multiple depth levels.")

# Drop useless columns

In [6]:
df = df.drop(columns=['depth'])

# Rename columns

In [7]:
rename_dict = {'time':'date'}
df = df.rename(columns=rename_dict)

In [8]:
df.head()

,latitude,longitude,date,chl,diatoC,diatoChla,dinoC,dinoChla,nanoC,nanoChla,phyc,picoC,picoChla,zooc
0,45.479168,13.166667,2024-01-01,0.432612,1.021826,0.045620,0.072453,0.003021,1.577424,0.132453,1.020759,9.577404,0.251518,1.292462
1,45.479168,13.166667,2024-01-02,0.409951,0.959496,0.042592,0.065867,0.002696,1.508388,0.125726,0.969965,9.105830,0.238936,1.269215
2,45.479168,13.166667,2024-01-03,0.387921,0.918257,0.040214,0.065525,0.002599,1.446924,0.118920,0.926805,8.690953,0.226188,1.249478
3,45.479168,13.166667,2024-01-04,0.367288,0.876112,0.037932,0.063349,0.002475,1.385913,0.112419,0.885613,8.301986,0.214462,1.226269
4,45.479168,13.166667,2024-01-05,0.347252,0.804106,0.034945,0.050663,0.002009,1.309341,0.106248,0.834719,7.852520,0.204050,1.191745

# Export

In [9]:
df.to_parquet(out, index=False)